apache:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysqldb:mysqldb

  volumes:
    - ./www:/var/www/html
    - ./logs:/var/log/apache2

mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
    volumes:
      - my-db:/var/lib/mysql
